"""All built-in inspectors are auto-registered when this package is imported."""

from debug_agent.inspectors import (  # noqa: F401
    async_tasks,
    cache_inspector,
    celery,
    config_inspector,
    database,
    django,
    endpoint_test_inspector,
    error_tracking,
    fastapi_ext,
    feature_flag_inspector,
    fd_inspector,
    flask_ext,
    framework,
    health_inspector,
    http_client_inspector,
    http_tracker,
    jinja2,
    locks_inspector,
    logging_inspector,
    memory,
    metrics_inspector,
    migration_inspector,
    modules,
    pool_inspector,
    redis,
    runtime,
    scheduler_inspector,
    security_inspector,
    signals,
    system,
    threads,
    warnings_inspector,
    websocket_inspector,
)
