"""All built-in inspectors are auto-registered when this package is imported."""

from debug_agent.inspectors import (  # noqa: F401
    async_tasks,
    cache_inspector,
    celery,
    database,
    django,
    fastapi_ext,
    fd_inspector,
    flask_ext,
    framework,
    http_client_inspector,
    http_tracker,
    jinja2,
    logging_inspector,
    memory,
    metrics_inspector,
    modules,
    redis,
    runtime,
    signals,
    system,
    threads,
    warnings_inspector,
)
